#CREATE A FILE 'config.py' IN THIS DIRECTORY
#'config.py' is in .gitignore
#COPY AND PASTE THIS FILE, EDIT RELEVANT FIELDS


TWITTER_CONSUMER_TOKEN = '<FOUND UNDER TWITTER APPS ACCESS TOKEN>'
TWITTER_CONSUMER_SECRET = '<FOUND UNDER TWITTER APPS ACCESS TOKEN SECRET>'
