#CREATE A FILE 'config.py' IN THIS DIRECTORY
#'config.py' is in .gitignore
#COPY AND PASTE THIS FILE, EDIT RELEVANT FIELDS
#KEYS FOUND UNDER 'https://apps.twitter.com/'

TWITTER_CONSUMER_KEY = ''
TWITTER_CONSUMER_SECRET = ''

TWITTER_ACCESS_TOKEN = ''
TWITTER_ACCESS_SECRET = ''
